//
// Generated file, do not edit! Created by opp_msgtool 6.1 from src/Request.msg.
//

#ifndef __REQUEST_M_H
#define __REQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class Request;
/**
 * Class generated from <tt>src/Request.msg:19</tt> by opp_msgtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet Request
 * {
 *     int src;      // ID della ECU che invia la richiesta
 *     int dest;     // ID della ECU destinataria
 *     string payload;
 *     string key;
 * }
 * </pre>
 */
class Request : public ::omnetpp::cPacket
{
  protected:
    int src = 0;
    int dest = 0;
    omnetpp::opp_string payload;
    omnetpp::opp_string key;

  private:
    void copy(const Request& other);

  protected:
    bool operator==(const Request&) = delete;

  public:
    Request(const char *name=nullptr, short kind=0);
    Request(const Request& other);
    virtual ~Request();
    Request& operator=(const Request& other);
    virtual Request *dup() const override {return new Request(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSrc() const;
    virtual void setSrc(int src);

    virtual int getDest() const;
    virtual void setDest(int dest);

    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);

    virtual const char * getKey() const;
    virtual void setKey(const char * key);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Request& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Request& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline Request *fromAnyPtr(any_ptr ptr) { return check_and_cast<Request*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __REQUEST_M_H

