#define HSM_RSA_REQUEST 0
#define HSM_RSA_RESPONSE 1
#define HSM_NS_REQUEST 2
#define HSM_NS_RESPONSE_SENDER 3
#define HSM_NS_RESPONSE_RECEIVER 4

#define IV_LEN 12
#define TAG_LEN 16
#define ECUID_LEN 8

#define AES_GCM_IV_SIZE 12
#define AES_GCM_TAG_SIZE 16

#define AAD_SIZE 8
